name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: vedantmgoyal2009/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: alexx2000.DoubleCommander
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
